# 端口
server:
  port: 8081

# 数据库配置
spring:
  # 数据源：druid
  datasource:
    name: myblog
    type: com.alibaba.druid.pool.DruidDataSource

    # druid 相关配置
    druid:
      # 监控统计拦截的filters
      # stat:监控统计、slf4j：日志记录、wall：防御sql注入
      filters: stat,wall,slf4j
      # mysql 驱动（最好使用新的）
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 基本链接
      url: jdbc:mysql://127.0.0.1:3306/myblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: HildaData
      password: 22222l22222123
      # 配置初始化
      initial-size: 1
      max-active: 20
      # 获取链接最长等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检查，检查需要关闭的空闲链接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 测试相关
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表多推荐设为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  # thymeleaf 配置
  thymeleaf:
    # 静态资源路径
    prefix: classpath:/templates/
    check-template-location: true
    # 指定后缀
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    # 关闭缓存
    cache: false

  # 配置 aop
  aop:
    auto: true
    proxy-target-class: true

  # servlet 配置（文件上传与下载）
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


# mybatis 相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.quan.myblog.pojo


# 日志相关
logging:
  level:
    com.quan.dao: DEBUG
    druid:
      sql:
        Statement: debug



